---
title: "Title"
author: "Authors"
format:
  pdf:
    fontsize: 12pt
editor: visual
execute: 
  echo: false
  message: false
  warning: false
abstract:
  This is an abstract
---

```{r, message=FALSE, warning=FALSE}
#Libraries

library(causaldata)
library(dagitty)
library(ggdag)
library(tidyverse)
library(knitr)
library(naniar)
library(gtsummary)
library(gt)
library(broom)
library(readxl)
library(propensity)
library(halfmoon)
library(patchwork)
library(tidysmd)
library(survey)

data("castle")
```


```{r}
castle_for_tab <- castle |> 
  select(!(starts_with("r20") |
             starts_with("trend") |
             starts_with("lead") |
             starts_with("lag"))) 

miss_tab <- miss_var_summary(castle_for_tab)
colnames(miss_tab) <- c("Variable", "Missing (n)", "Percent Missing")
miss_tab %>%
  gt()
```


```{r}
# Data transforms
castle$treat_year <- ifelse(castle$post == 1, castle$year, 0)

lower <- 1
upper <- 11
i <- 1
while(i < 51){
  treat_year_1 <- min(castle$treat_year[lower:upper][castle$treat_year[lower:upper] != 0])
  castle$treat_year[lower:upper] <- rep(treat_year_1, 11)
  lower <- upper + 1
  upper <- lower + 10
  i <- i + 1
}

castle <- castle %>%
  mutate(years_after_treat = year - treat_year)

castle$years_after_treat <- ifelse(castle$years_after_treat == -Inf, NA, castle$years_after_treat)


castle <- castle %>%
  group_by(sid) %>%
  mutate_at(c("assault", "burglary", "larceny", "motor", "l_larceny", "l_motor", 
              "l_police", "l_income", "l_exp_subsidy", "l_exp_pubwelfare"), lag) %>%
  mutate(murder_lag = lag(murder)) %>% 
  ungroup()


castle$sid <- ifelse(as.numeric(castle$sid) > 8, castle$sid - 1, castle$sid)

state_id_ranks <- read_excel("state_id_ranks.xlsx", col_names = FALSE)
colnames(state_id_ranks) <- c("state", "pop", "sid")
state_id_ranks <- state_id_ranks %>%
  select(state, sid)
castle_dat <- full_join(castle, state_id_ranks, by = "sid")

castle_dat <- castle_dat[castle_dat$year != 2000,]


castle_dat <- castle_dat |> 
  select(!(starts_with("r20") |
             starts_with("trend") |
             starts_with("lead") |
             starts_with("lag"))) %>%
  drop_na(robbery_gun_r)
```


#DAG

```{r}
# young_male_race is taking place of blackm_15_24 + whitem_15_24 + blackm_25_44 + whitem_25_44

castle_dag <- dagify(
  murder ~ young_male_race + poverty + popwt + robbery_gun_r + l_police + post + years_after_treat + robbery,
  
  post ~ homicide + robbery_gun_r + assault + burglary + larceny + motor + murder_lag + robbery,
  
  burglary ~ poverty + young_male_race,
  homicide ~ poverty + young_male_race,
  larceny ~ poverty + young_male_race,
  motor ~ poverty + young_male_race,
  robbery ~ poverty + young_male_race,
  assault ~ poverty + young_male_race,
  
  poverty ~ unemployrt + l_exp_subsidy + l_exp_pubwelfare + l_income,
  
  l_police ~ l_income,
  
  outcome = "murder",
  exposure = "post",
  labels = c(
    murder = "Murder",
    murder_lag = "Murder Lagged",
    unemployrt = "Unemployment",
    young_male_race = "Male Demo.",
    poverty = "Poverty",
    popwt = "Population",
    robbery_gun_r = "Armed Robbery Prop.",
    l_exp_subsidy = "Subsidy",
    l_exp_pubwelfare = "Welfare",
    l_police = "Police",
    post = "Castle Doctrine",
    years_after_treat = "Years Post Castle",
    
    homicide = "Homicides",
    robbery = "Robbery",
    assault = "Assaults",
    burglary = "Burglary",
    larceny = "Larceny",
    motor = "Auto Theft",
    l_income = "Income")
)


```

```{r, fig.height=10, fig.width=10}
ggdag(castle_dag, layout = "nicely", use_labels = "label", text = FALSE) +
  theme_dag()

```


```{r, fig.height=10, fig.width=10}
# ggdag_adjustment_set(castle_dag, text_col = "black") +
#   theme_dag()
adjustmentSets(castle_dag)
```

```{r}
castle_select <- castle_dat %>%
  select(c(post, poverty, robbery, robbery_gun_r, whitem_15_24, blackm_15_24, whitem_25_44, blackm_25_44)) |> 
  mutate(post = ifelse(post == 0, "Pre-Doctrine", "Post-Doctrine"))

castle_select_2 <- castle_dat |> 
  select(c(post, assault, burglary, homicide, larceny, motor, robbery, robbery_gun_r)) |> 
  mutate(post = ifelse(post == 0, "Pre-Doctrine", "Post-Doctrine"))

tbl_summary(
  castle_select,
  by = post
) %>%
  add_overall(last = TRUE)

tbl_summary(
  castle_select_2,
  by = post
) %>%
  add_overall(last = TRUE)
```


# Propensity Scores:

```{r}
castle_w_ps <- 
  glm(post ~ assault + burglary + homicide + larceny + motor + robbery + robbery_gun_r, data = castle_dat, family = binomial()) |> 
    augment(type.predict = "response", data = castle_dat)

ggplot(castle_w_ps, aes(.fitted, fill = factor(post))) +
  geom_mirror_histogram(bins = 50) +
  scale_y_continuous(labels = abs) +
  labs(x = "Propensity Score", y= "Count", fill = "Castle Doctrine",
       title = "Mirrored Histograms of Propensity Scores by Castle Doctrine") +
  scale_fill_manual(
    "Castle Doctrine",
    values = c("turquoise", "coral"),
    labels = c("Pre", "Post")
  )

```

```{r}
castle_wts <- castle_w_ps |> 
  mutate(w_att = wt_att(.fitted, post),
         w_ato = wt_ato(.fitted, post),
    post = factor(
      post, 
      labels = c("Pre", "Post")
    )
)

head(castle_wts)

```


```{r}
#ATO TABLE
svy_des <- svydesign(
  ids = ~1,
  data = castle_wts,
  weights = ~ w_ato
)

hdr <- paste0(
  "**{level}**  \n",
  "N = {n_unweighted}; ESS = {format(n, digits = 1, nsmall = 1)}"
)

tbl_svysummary(svy_des, by = post,
               include = c(post, assault, burglary, homicide, larceny, motor, robbery, robbery_gun_r)
               )|> 
    add_overall(last = TRUE) |> 
  add_ess_header(header = hdr)

#ATT TABLE
svy_des <- svydesign(
  ids = ~1,
  data = castle_wts,
  weights = ~ w_att
)

hdr <- paste0(
  "**{level}**  \n",
  "N = {n_unweighted}; ESS = {format(n, digits = 1, nsmall = 1)}"
)

tbl_svysummary(svy_des, by = post,
               include = c(post, assault, burglary, homicide, larceny, motor, robbery, robbery_gun_r)
               )|> 
    add_overall(last = TRUE) |> 
  add_ess_header(header = hdr)

```


```{r, message = FALSE}
#ATO
ggplot(castle_wts, aes(.fitted, group = factor(post))) +
  geom_mirror_histogram(bins = 50, alpha = 0.5) +
  geom_mirror_histogram(
    aes(fill = post, weight = w_ato),
    bins = 50,
    alpha = 1) +
  scale_y_continuous(labels = abs) +
  labs(x = "Propensity Score", y= "Count", fill = "Castle Doctrine",
       title = "Mirrored Histograms of Propensity Scores by Castle Doctrine",
       subtitle = "Compared to Unweighted Populations") +
  scale_fill_manual(
    "Castle Doctrine",
    values = c("turquoise", "coral"),
    labels = c("Pre", "Post")
  )

#ATT
ggplot(castle_wts, aes(.fitted, group = factor(post))) +
  geom_mirror_histogram(
    aes(fill = post, weight = w_att),
    bins = 30,
    alpha = 1) +
  scale_y_continuous(labels = abs) +
  labs(x = "Propensity Score", y= "Count", fill = "Castle Doctrine",
       title = "Mirrored Histograms of Propensity Scores by Castle Doctrine") +
  scale_fill_manual(
    "Castle Doctrine",
    values = c("turquoise", "coral"),
    labels = c("Pre", "Post")
)

```

```{r}
#ATO
smds <- tidy_smd(
  castle_wts,
  .vars = c(assault, burglary, homicide, larceny, motor, robbery, robbery_gun_r),
  .group = post,
  .wts = c(w_ato)
)

ggplot(
  data = smds,
  aes(
    x = abs(smd),
    y = variable,
    group = method,
    color = method
  )
) +
  geom_love() +
  scale_color_manual(labels = c("Observed","ATO Weighted"),
                     values = c("turquoise", "coral")) +
  labs(x = "Absolute Value of Standardized Mean Difference",
         y = "Covariate", title = "Love Plot of Standardized Mean Difference",
       subtitle = "Observed SMD vs. ATO Weighted SMD")

#ATT
smds2 <- tidy_smd(
  castle_wts,
  .vars = c(assault, burglary, homicide, motor, robbery, robbery_gun_r),
  .group = post,
  .wts = c(w_att)
)

ggplot(
  data = smds2,
  aes(
    x = abs(smd),
    y = variable,
    group = method,
    color = method
  )
) +
  geom_love() +
  scale_color_manual(labels = c("Observed","ATT Weighted"),
                     values = c("turquoise", "coral")) +
  labs(x = "Absolute Value of Standardized Mean Difference",
         y = "Covariate", title = "Love Plot of Standardized Mean Difference",
       subtitle = "Observed SMD vs. ATT Weighted SMD")


```



```{r}
ggplot(
  castle_wts,
  aes(x = robbery_gun_r,
      color = factor(post))
) +
  geom_ecdf() +
  scale_color_manual(
    "Castle Doctrine",
    values = c("turquoise", "coral"),
    labels = c("Pre", "Post")
  )+
  labs(x = "Robbery Gun Rate", y = "Proportion <= x",
       title = "Emperical CDFs of RGR",
       subtitle = "Comparisson of Pre/Post Castle Doctrine")


ggplot(
  castle_wts,
  aes(x = robbery_gun_r,
      color = factor(post))
) +
  geom_ecdf(aes(weights = w_ato)) +
  scale_color_manual(
    "Castle Doctrine",
    values = c("turquoise", "coral"),
    labels = c("Pre", "Post")
  )+
  labs(x = "Robbery Gun Rate", y = "Proportion <= x",
       title = "Emperical CDFs of RGR",
       subtitle = "Comparisson of Pre/Post Castle Doctrine")


```
```{r}
ggplot(
  castle_wts,
  aes(x = robbery,
      color = factor(post))
) +
  geom_ecdf() +
  scale_color_manual(
    "Castle Doctrine",
    values = c("turquoise", "coral"),
    labels = c("Pre", "Post")
  )+
  labs(x = "Robbery", y = "Proportion <= x",
       title = "Emperical CDFs of Robbery",
       subtitle = "Comparisson of Pre/Post Castle Doctrine")


ggplot(
  castle_wts,
  aes(x = robbery,
      color = factor(post))
) +
  geom_ecdf(aes(weights = w_ato)) +
  scale_color_manual(
    "Castle Doctrine",
    values = c("turquoise", "coral"),
    labels = c("Pre", "Post")
  )+
  labs(x = "Robbery", y = "Proportion <= x",
       title = "Emperical CDFs of Robbery",
       subtitle = "Comparisson of Pre/Post Castle Doctrine")


```


```{r}
ggplot(
  castle_wts,
  aes(x = motor,
      color = factor(post))
) +
  geom_ecdf() +
  scale_color_manual(
    "Castle Doctrine",
    values = c("turquoise", "coral"),
    labels = c("Pre", "Post")
  )+
  labs(x = "Motor Theft Rate", y = "Proportion <= x",
       title = "Emperical CDFs of Motor",
       subtitle = "Comparisson of Pre/Post Castle Doctrine")


ggplot(
  castle_wts,
  aes(x = motor,
      color = factor(post))
) +
  geom_ecdf(aes(weights = w_ato)) +
  scale_color_manual(
    "Castle Doctrine",
    values = c("turquoise", "coral"),
    labels = c("Pre", "Post")
  )+
  labs(x = "Motor Theft Rate", y = "Proportion <= x",
       title = "Emperical CDFs of Motor",
       subtitle = "Comparisson of Pre/Post Castle Doctrine")


```


```{r}
ggplot(
  castle_wts,
  aes(x = larceny,
      color = factor(post))
) +
  geom_ecdf() +
  scale_color_manual(
    "Castle Doctrine",
    values = c("turquoise", "coral"),
    labels = c("Pre", "Post")
  )+
  labs(x = "Larceny Rate", y = "Proportion <= x",
       title = "Emperical CDFs of Larceny",
       subtitle = "Comparisson of Pre/Post Castle Doctrine")


ggplot(
  castle_wts,
  aes(x = larceny,
      color = factor(post))
) +
  geom_ecdf(aes(weights = w_ato)) +
  scale_color_manual(
    "Castle Doctrine",
    values = c("turquoise", "coral"),
    labels = c("Pre", "Post")
  )+
  labs(x = "Larceny Rate", y = "Proportion <= x",
       title = "Emperical CDFs of Larceny",
       subtitle = "Comparisson of Pre/Post Castle Doctrine")


```


```{r}
ggplot(
  castle_wts,
  aes(x = homicide,
      color = factor(post))
) +
  geom_ecdf() +
  scale_color_manual(
    "Castle Doctrine",
    values = c("turquoise", "coral"),
    labels = c("Pre", "Post")
  )+
  labs(x = "Homicide Rate", y = "Proportion <= x",
       title = "Emperical CDFs of Homicide",
       subtitle = "Comparisson of Pre/Post Castle Doctrine")


ggplot(
  castle_wts,
  aes(x = homicide,
      color = factor(post))
) +
  geom_ecdf(aes(weights = w_ato)) +
  scale_color_manual(
    "Castle Doctrine",
    values = c("turquoise", "coral"),
    labels = c("Pre", "Post")
  )+
  labs(x = "Homicide Rate", y = "Proportion <= x",
       title = "Emperical CDFs of Homicide",
       subtitle = "Comparisson of Pre/Post Castle Doctrine")


```


```{r}
ggplot(
  castle_wts,
  aes(x = burglary,
      color = factor(post))
) +
  geom_ecdf() +
  scale_color_manual(
    "Castle Doctrine",
    values = c("turquoise", "coral"),
    labels = c("Pre", "Post")
  )+
  labs(x = "Burglary Rate", y = "Proportion <= x",
       title = "Emperical CDFs of Burglary",
       subtitle = "Comparisson of Pre/Post Castle Doctrine")


ggplot(
  castle_wts,
  aes(x = burglary,
      color = factor(post))
) +
  geom_ecdf(aes(weights = w_ato)) +
  scale_color_manual(
    "Castle Doctrine",
    values = c("turquoise", "coral"),
    labels = c("Pre", "Post")
  )+
  labs(x = "Burglary Rate", y = "Proportion <= x",
       title = "Emperical CDFs of Burglary",
       subtitle = "Comparisson of Pre/Post Castle Doctrine")


```


```{r}
ggplot(
  castle_wts,
  aes(x = assault,
      color = factor(post))
) +
  geom_ecdf() +
  scale_color_manual(
    "Castle Doctrine",
    values = c("turquoise", "coral"),
    labels = c("Pre", "Post")
  )+
  labs(x = "Assault Rate", y = "Proportion <= x",
       title = "Emperical CDFs of Assault",
       subtitle = "Comparisson of Pre/Post Castle Doctrine")


ggplot(
  castle_wts,
  aes(x = assault,
      color = factor(post))
) +
  geom_ecdf(aes(weights = w_ato)) +
  scale_color_manual(
    "Castle Doctrine",
    values = c("turquoise", "coral"),
    labels = c("Pre", "Post")
  )+
  labs(x = "Assault Rate", y = "Proportion <= x",
       title = "Emperical CDFs of Assault",
       subtitle = "Comparisson of Pre/Post Castle Doctrine")


```


## New Model

```{r}
castle_w_ps_2 <- 
  glm(post ~ #splines::ns(assault,2) +
        assault +
        splines::ns(burglary, df = 6) +
        splines::ns(homicide, df = 5) +
       # splines::ns(larceny, df = 2) +
        motor + robbery + robbery_gun_r, data = castle_dat, family = binomial()) |> 
    augment(type.predict = "response", data = castle_dat)

castle_wts_2 <- castle_w_ps_2 |> 
  mutate(w_ato = wt_ato(.fitted, post),
         w_att = wt_att(.fitted, post),
         post = factor(post,
  labels = c("Pre", "Post"))
  )

```



```{r, message = FALSE}
#ATO
ggplot(castle_wts_2, aes(.fitted, group = factor(post))) +
#  geom_mirror_histogram(bins = 50, alpha = 0.5) +
  geom_mirror_histogram(
    aes(fill = post, weight = w_ato),
    bins = 50,
    alpha = 1) +
  scale_y_continuous(labels = abs) +
  labs(x = "Propensity Score", y= "Count", fill = "Castle Doctrine",
       title = "ATO Mirrored Histograms of Propensity Scores by Castle Doctrine",
       subtitle = "Compared to Unweighted Populations") +
  scale_fill_manual(
    "Castle Doctrine",
    values = c("turquoise", "coral"),
    labels = c("Pre", "Post")
  )

#ATT
ggplot(castle_wts_2, aes(.fitted, group = factor(post))) +
  geom_mirror_histogram(
    aes(fill = post, weight = w_att),
    bins = 30,
    alpha = 1) +
  scale_y_continuous(labels = abs) +
  labs(x = "Propensity Score", y= "Count", fill = "Castle Doctrine",
       title = "ATT Mirrored Histograms of Propensity Scores by Castle Doctrine") +
  scale_fill_manual(
    "Castle Doctrine",
    values = c("turquoise", "coral"),
    labels = c("Pre", "Post")
)

```

```{r}
#ATO
smds <- tidy_smd(
  castle_wts_2,
  .vars = c(assault, burglary, homicide, motor, robbery, robbery_gun_r),
  .group = post,
  .wts = c(w_ato)
)

ggplot(
  data = smds,
  aes(
    x = abs(smd),
    y = variable,
    group = method,
    color = method
  )
) +
  geom_love() +
  scale_color_manual(labels = c("Observed","ATO Weighted"),
                     values = c("turquoise", "coral")) +
  labs(x = "Absolute Value of Standardized Mean Difference",
         y = "Covariate", title = "Love Plot of Standardized Mean Difference",
       subtitle = "Observed SMD vs. ATO Weighted SMD")

#ATT
smds2 <- tidy_smd(
  castle_wts_2,
  .vars = c(assault, burglary, homicide, motor, robbery, robbery_gun_r),
  .group = post,
  .wts = c(w_att)
)

ggplot(
  data = smds2,
  aes(
    x = abs(smd),
    y = variable,
    group = method,
    color = method
  )
) +
  geom_love() +
  scale_color_manual(labels = c("Observed","ATT Weighted"),
                     values = c("turquoise", "coral")) +
  labs(x = "Absolute Value of Standardized Mean Difference",
         y = "Covariate", title = "Love Plot of Standardized Mean Difference",
       subtitle = "Observed SMD vs. ATT Weighted SMD")


```



```{r}
ggplot(
  castle_wts_2,
  aes(x = robbery_gun_r,
      color = factor(post))
) +
  geom_ecdf() +
  scale_color_manual(
    "Castle Doctrine",
    values = c("turquoise", "coral"),
    labels = c("Pre", "Post")
  )+
  labs(x = "Robbery Gun Rate", y = "Proportion <= x",
       title = "Emperical CDFs of RGR",
       subtitle = "Comparisson of Pre/Post Castle Doctrine")


ggplot(
  castle_wts_2,
  aes(x = robbery_gun_r,
      color = factor(post))
) +
  geom_ecdf(aes(weights = w_att)) +
  scale_color_manual(
    "Castle Doctrine",
    values = c("turquoise", "coral"),
    labels = c("Pre", "Post")
  )+
  labs(x = "Robbery Gun Rate", y = "Proportion <= x",
       title = "Emperical CDFs of RGR",
       subtitle = "Comparisson of Pre/Post Castle Doctrine")


```
```{r}
ggplot(
  castle_wts_2,
  aes(x = robbery,
      color = factor(post))
) +
  geom_ecdf() +
  scale_color_manual(
    "Castle Doctrine",
    values = c("turquoise", "coral"),
    labels = c("Pre", "Post")
  )+
  labs(x = "Robbery", y = "Proportion <= x",
       title = "Emperical CDFs of Robbery",
       subtitle = "Comparisson of Pre/Post Castle Doctrine")


ggplot(
  castle_wts_2,
  aes(x = robbery,
      color = factor(post))
) +
  geom_ecdf(aes(weights = w_att)) +
  scale_color_manual(
    "Castle Doctrine",
    values = c("turquoise", "coral"),
    labels = c("Pre", "Post")
  )+
  labs(x = "Robbery", y = "Proportion <= x",
       title = "Emperical CDFs of Robbery",
       subtitle = "Comparisson of Pre/Post Castle Doctrine")


```


```{r}
ggplot(
  castle_wts_2,
  aes(x = motor,
      color = factor(post))
) +
  geom_ecdf() +
  scale_color_manual(
    "Castle Doctrine",
    values = c("turquoise", "coral"),
    labels = c("Pre", "Post")
  )+
  labs(x = "Motor Theft Rate", y = "Proportion <= x",
       title = "Emperical CDFs of Motor",
       subtitle = "Comparisson of Pre/Post Castle Doctrine")


ggplot(
  castle_wts_2,
  aes(x = motor,
      color = factor(post))
) +
  geom_ecdf(aes(weights = w_att)) +
  scale_color_manual(
    "Castle Doctrine",
    values = c("turquoise", "coral"),
    labels = c("Pre", "Post")
  )+
  labs(x = "Motor Theft Rate", y = "Proportion <= x",
       title = "Emperical CDFs of Motor",
       subtitle = "Comparisson of Pre/Post Castle Doctrine")


```


```{r}
ggplot(
  castle_wts_2,
  aes(x = larceny,
      color = factor(post))
) +
  geom_ecdf() +
  scale_color_manual(
    "Castle Doctrine",
    values = c("turquoise", "coral"),
    labels = c("Pre", "Post")
  )+
  labs(x = "Larceny Rate", y = "Proportion <= x",
       title = "Emperical CDFs of Larceny",
       subtitle = "Comparisson of Pre/Post Castle Doctrine")


ggplot(
  castle_wts_2,
  aes(x = larceny,
      color = factor(post))
) +
  geom_ecdf(aes(weights = w_att)) +
  scale_color_manual(
    "Castle Doctrine",
    values = c("turquoise", "coral"),
    labels = c("Pre", "Post")
  )+
  labs(x = "Larceny Rate", y = "Proportion <= x",
       title = "Emperical CDFs of Larceny",
       subtitle = "Comparisson of Pre/Post Castle Doctrine")


```


```{r}
ggplot(
  castle_wts_2,
  aes(x = homicide,
      color = factor(post))
) +
  geom_ecdf() +
  scale_color_manual(
    "Castle Doctrine",
    values = c("turquoise", "coral"),
    labels = c("Pre", "Post")
  )+
  labs(x = "Homicide Rate", y = "Proportion <= x",
       title = "Emperical CDFs of Homicide",
       subtitle = "Comparisson of Pre/Post Castle Doctrine")


ggplot(
  castle_wts_2,
  aes(x = homicide,
      color = factor(post))
) +
  geom_ecdf(aes(weights = w_att)) +
  scale_color_manual(
    "Castle Doctrine",
    values = c("turquoise", "coral"),
    labels = c("Pre", "Post")
  )+
  labs(x = "Homicide Rate", y = "Proportion <= x",
       title = "Emperical CDFs of Homicide",
       subtitle = "Comparisson of Pre/Post Castle Doctrine")


```


```{r}
ggplot(
  castle_wts_2,
  aes(x = burglary,
      color = factor(post))
) +
  geom_ecdf() +
  scale_color_manual(
    "Castle Doctrine",
    values = c("turquoise", "coral"),
    labels = c("Pre", "Post")
  )+
  labs(x = "Burglary Rate", y = "Proportion <= x",
       title = "Emperical CDFs of Burglary",
       subtitle = "Comparisson of Pre/Post Castle Doctrine")


ggplot(
  castle_wts_2,
  aes(x = burglary,
      color = factor(post))
) +
  geom_ecdf(aes(weights = w_att)) +
  scale_color_manual(
    "Castle Doctrine",
    values = c("turquoise", "coral"),
    labels = c("Pre", "Post")
  )+
  labs(x = "Burglary Rate", y = "Proportion <= x",
       title = "Emperical CDFs of Burglary",
       subtitle = "Comparisson of Pre/Post Castle Doctrine")


```


```{r}
ggplot(
  castle_wts_2,
  aes(x = assault,
      color = factor(post))
) +
  geom_ecdf() +
  scale_color_manual(
    "Castle Doctrine",
    values = c("turquoise", "coral"),
    labels = c("Pre", "Post")
  )+
  labs(x = "Assault Rate", y = "Proportion <= x",
       title = "Emperical CDFs of Assault",
       subtitle = "Comparisson of Pre/Post Castle Doctrine")


ggplot(
  castle_wts_2,
  aes(x = assault,
      color = factor(post))
) +
  geom_ecdf(aes(weights = w_att)) +
  scale_color_manual(
    "Castle Doctrine",
    values = c("turquoise", "coral"),
    labels = c("Pre", "Post")
  )+
  labs(x = "Assault Rate", y = "Proportion <= x",
       title = "Emperical CDFs of Assault",
       subtitle = "Comparisson of Pre/Post Castle Doctrine")


```


```{r}

#ATT TABLE
svy_des <- svydesign(
  ids = ~1,
  data = castle_wts_2,
  weights = ~ w_att
)

hdr <- paste0(
  "**{level}**  \n",
  "N = {n_unweighted}; ESS = {format(n, digits = 1, nsmall = 1)}"
)

tbl_svysummary(svy_des, by = post,
               include = c(post, assault, burglary, homicide, motor, robbery, robbery_gun_r)
               )|> 
    add_overall(last = TRUE) |> 
  add_ess_header(header = hdr)


```